# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.5.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ZeekoZhu
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{secrets.GITHUB_TOKEN}}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io/zeekozhu/no-profile-web
      - name: Build no-profile-api
        uses: docker/build-push-action@v4.0.0
        with:
          tags: ghcr.io/zeekozhu/no-profile-api:latest
          context: ${{github.workspace}}/src/NoProfile.Api
          file: ${{github.workspace}}/src/NoProfile.Api/Dockerfile
          push: true
  build-web:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.5.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          # Username used to log in to a Docker registry. If not set then no login will occur
          username: ZeekoZhu
          # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
          password: ${{secrets.GITHUB_TOKEN}}
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: ghcr.io/zeekozhu/no-profile-web
      - name: Build no-profile-web
        uses: docker/build-push-action@v4.0.0
        with:
          tags: ghcr.io/zeekozhu/no-profile-web:latest
          context: ${{github.workspace}}/src/client-app
          file: ${{github.workspace}}/src/client-app/Dockerfile
          push: true
